name: Security Pipeline (SAST, Secrets, Container)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: "0 3 * * 1"   # Her Pazartesi 06:00 TR saati civarı (UTC+3)
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write   # Code scanning/SARIF upload için şart
  packages: read

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # --- SAST (CodeQL Advanced / Java) ---
  codeql-java:
    name: SAST (CodeQL Java - security-extended)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
  
      - name: Initialize CodeQL (Java)
        uses: github/codeql-action/init@v3
        with:
          languages: java
          queries: +security-extended
          build-mode: manual    # derlenen dillerde DB için build şart
  
      - name: Build for CodeQL DB
        run: mvn -q -DskipTests -pl webgoat-server -am package
  
      - name: Analyze (Java)
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"

# --- SAST (CodeQL - JavaScript/TypeScript) ---
  codeql-js:
    name: SAST (CodeQL JS/TS - security-extended)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Initialize CodeQL (JS/TS)
        uses: github/codeql-action/init@v3
        with:
          languages: javascript      # TypeScript’i de kapsar
          queries: +security-extended
          build-mode: none           # JS/TS için build gerekmiyor
  
      - name: Analyze (JS/TS)
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"

  # --- Secrets (TruffleHog) ---
  trufflehog:
    name: Secrets (TruffleHog)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # TruffleHog GitHub Action — belirli v3 sürümüne pinliyoruz
      - name: Run TruffleHog (git history)
        uses: trufflesecurity/trufflehog@v3.90.11
        with:
            # Doğrulanmış bulgulara odaklan (false-positive azaltır)
            extra_args: --results=verified --only-verified
            github-token: ${{ secrets.GITHUB_TOKEN }}


  # --- Container Image Tarama (Trivy + Grype) ---
  container-scan:
    name: Container Scan (Trivy + Grype)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Projede Dockerfile var → image build et
      - name: Build image
        run: |
          docker build -t app-under-test:ci .

      # Trivy ile image zafiyet taraması (SARIF)
      - name: Trivy scan (image)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --scanners vuln \
            --format sarif -o trivy.sarif \
            app-under-test:ci || true

      - name: Upload SARIF (Trivy)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
          category: trivy

      # Grype ile image zafiyet taraması (SARIF)
      - name: Grype scan (image)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            anchore/grype:latest \
            app-under-test:ci -o sarif > grype.sarif || true

      - name: Upload SARIF (Grype)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype.sarif
          category: grype
