name: Security Pipeline (WebGoat)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  sast-semgrep:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        run: |
          docker run --rm -v "$PWD:/src" -w /src returntocorp/semgrep:latest \
          semgrep --config p/owasp-top-ten --metrics=off --sarif -o semgrep.sarif || true

      - name: Upload Semgrep results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep

